### ISSUE TITLE
Allow plugins to extend the CLI

### ISSUE THREAD

**Issue by fvsch** [getkirby-v2/cli#22]
I’d like to be able to write functions/methods in a plugin that could be called with:

```
kirby pluginname:command [params]
```

Use case: I’d like to add CLI support to the StaticBuilder plugin.
See: https://github.com/fvsch/kirby-staticbuilder/issues/4

Maybe something as basic as looking for a `$kirby->roots()->plugins() . DS . $pluginname . DS . 'cli.php'` file for unknown command prefix (or namespace or however it’s called, I mean the part before the colon)? And specifying how it should be written, maybe like:

``` php
<?php // site/plugins/myplugin/cli.php

namespace Kirby\Cli;

class MypluginSomethingCommand extends BaseCommand {
  protected function something() {
  }
}
```

I just skimmed the cli source, not sure what would make sense.

**Comment by jenstornell** [comment]
It would probably mean more stuff in the CLI and Bastian don't have to do everything.

+1
