### ISSUE TITLE
Feature: Install with custom kit

### ISSUE THREAD

**Issue by RobertCordes** [getkirby-v2/cli#23]
Hi,

not sure what would be the best way to do this but it would be great if I could create my own starterkit to use with a new kirby install.

**Comment by lukasbestle** [comment]
What the CLI could do is to clone a theme repository from GitHub and put in the latest Kirby version. So you would basically point the CLI to a URL of your custom kit.

**Comment by RobertCordes** [comment]
Yeah. Maybe the way you do it with plugins, to keep it consistent.

**Comment by acstll** [comment]
I was just thinking about this : )

Would a PR be welcomed?

The logic could be very simple, if `$name` contains a slash then

```php
$url  = 'https://github.com/getkirby/' . $name . '/archive/master.zip';$url  = 'https://github.com/getkirby/' . $name . '/archive/master.zip';
```

should be

```php
$url  = 'https://github.com/' . $name . '/archive/master.zip';$url  = 'https://github.com/getkirby/' . $name . '/archive/master.zip';
```
https://github.com/getkirby/cli/blob/master/src/Util/Download.php#L54

What do you think @lukasbestle ?
