### ISSUE TITLE
Install Plugin from Subdirectory

### ISSUE THREAD

**Issue by florianpircher** [getkirby-v2/cli#24]
The current implementation of the `kirby plugin:install` command requires the plugin as well as the package.json to be located at the root level of a git repository.

Some plugins require other components (like snippets, blueprints, widgets, …) and are therefore located in a subdirectory of the git repository.

It would be nice to install such plugins by specifying the full path to the plugin.

``` bash
kirby plugin:install Addpixel/KirbyComments/comments # does not work
```

For testing proposes I have released [v1.1.1](https://github.com/Addpixel/KirbyComments/releases/tag/1.1.1) of my Kirby Comments plugin, which now contains the plugin as well as the package.json in the ./comments/ directory.

**Comment by lukasbestle** [comment]
The recommendation is to use the new registry from Kirby 2.3. It allows you to register snippets, blueprints, widgets etc. from your plugin. Your current directory structure can't be supported by the CLI very well as there will always be some manual work and automatic updates etc. won't work.
