### ISSUE TITLE
Extra Plugin Name Field

### ISSUE THREAD

**Issue by maxxst** [getkirby-v2/cli#26]
Right now the plugin name is defined by the `name: "xyz"` in package.json but I would prefer to have that name to be something like 'kirby-plugin-theName'.

So maybe one should omit substrings like `kirby-`, `-plugin-` and `-fieldtype-` from name. Or there could be like an extra (optional) field kirby-name to address this issue.

**Comment by jenstornell** [comment]
I have a similar "issue". I want to have the slug `kirby-plugin-name` on github but `plugin-name` in the plugin folder.

**Comment by maxxst** [comment]
this should be solvable with the name in package.json already
