### ISSUE TITLE
UTF8 errors

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/cli#27]
I use this:

```
{
  "name": "kirby-ratings",
  "description": "Rating stars for Kirby CMS",
  "author": "Jens Törnell <jens.tornell@gmail.com>",
  "version": "0.2",
  "type": "kirby-plugin",
  "license": "MIT"
}
```

![image](https://cloud.githubusercontent.com/assets/927011/18243231/7714af00-735a-11e6-86bf-4d10e8eb2ba8.png)

My auhor name "Törnell" is wrong.

**Comment by lukasbestle** [comment]
The output happens in [this method](https://github.com/getkirby/cli/blob/master/src/PluginCommand.php#L83-L114) and there is no code that could break with UTF-8 characters.

I have tested this locally and get the following:

<img width="496" alt="bildschirmfoto 2016-09-05 um 12 38 20" src="https://cloud.githubusercontent.com/assets/1595007/18245462/a926eaf2-7365-11e6-9950-8a4c6a7e8dad.png">

Seems to be your shell or terminal.

**Comment by jenstornell** [comment]
I'm using the preinstalled `cmd` in Windows 10. I guess all Windows 10 users will have the same issue then?

**Comment by lukasbestle** [comment]
Maybe [this helps](http://superuser.com/a/269857)?

**Comment by bastianallgeier** [comment]
@jenstornell Did you try Lukas' suggestion? Did it work?
