### ISSUE TITLE
Fatal error: Cannot redeclare e()

### ISSUE THREAD

**Issue by thomasverleye** [getkirby-v2/cli#3]
So I tried out the CLI, really love the idea!

It worked to install everything globally with composer and it seems to work. I can install a kirby starterpack with `kirby install` and it does what it needs to do.

But when I try to create a blueprint for instance it gives me a Fatal error.
I tried out `kirby make:blueprint test` and it gives me following error:

Thomass-MBP:kirby thomasverleye$ kirby make:blueprint test

Fatal error: Cannot redeclare e() (previously declared in /Users/thomasverleye/.composer/vendor/illuminate/support/helpers.php:523) in /Sites/kerckstede/kirby/kirby/toolkit/helpers.php on line 85

It seems to be a conflict with some other vendors I previously installed, I've already tried to update those vendor but that had no effect.
Any of you guys have experience with this kind of issues?

**Comment by thomasverleye** [comment]
At the moment I made it to work this way:
https://twitter.com/getkirby/status/704031445946408960

Offcourse it's not the ideal working process because if there are any updates in the near future i'll need to go to that folder and update the vendor manually.

**Comment by acstll** [comment]
I just ran into this issue.

I solved it by removing `.composer/vendor/illuminate/support` directly, and then running `composer global update`.

I previously ran `composer global why illuminate/support` and there was no package depending on it. I just couldn't find out why it was there…

Still, very annoying issue.
