### ISSUE TITLE
Additional parameter on install for specific version

### ISSUE THREAD

**Issue by npostulart** [getkirby-v2/cli#30]
It would be great to be able to install a specific version using the CLI.

e.g. `kirby install:core 2.3.2`

**Comment by maxxst** [comment]
I guess the easiest to would be to use options. The command would then be:

```
kirby install:core --version=2.3.2
```

**Comment by maxxst** [comment]
maybe it would be a good idea to start consuming the Github API ?

for versions see [Github API Releases](https://developer.github.com/v3/repos/releases/#get-a-single-release)

**Comment by maxxst** [comment]
I think in Pullrequest #33 you should see how it could be done (I'm working on integrating more of the Github API right now)

**Comment by bnomei** [comment]
much needed to rollback to an older version if a broken version is released like 2.5 just now (https://github.com/getkirby/panel/issues/1064).

**Comment by wottpal** [comment]
or 2.5.3/4 :( 
Not really concerned about bugs at all, they happen. But it would be great to simply roll back with one line instead of downloading it manually.
