### ISSUE TITLE
Conflicts with Symfony var-dumper

### ISSUE THREAD

**Issue by peschee** [getkirby-v2/cli#37]
Running `kirby version` (and some of the other commands, e.g. `kirby update`) fail with the error message:

```php
Fatal error: Cannot redeclare dump() (previously declared in ~/.composer/vendor/symfony/var-dumper/Resources/functions/dump.php:18) in ./kirby/kirby/vendor/getkirby/toolkit/helpers.php on line 114
```

when Symfony's [var-dumper component](https://packagist.org/packages/symfony/var-dumper) is installed globally (e.g. as a dependency of other packages).

**Comment by mightymango** [comment]
Had the same problem so just made the changes below to kirby/vendor/getkirby/toolkit/helpers.php.

```
if (!function_exists('dump')) {
	
	function dump($variable, $echo = true) {
	  if(r::cli()) {
	    $output = print_r($variable, true) . PHP_EOL;
	  } else {
	    $output = '<pre>' . print_r($variable, true) . '</pre>';
	  }
	  if($echo === true) echo $output;
	  return $output;
	}

}
```

**Comment by alancwoo** [comment]
I'm also unfortunately having this problem on multiple machines, is there a reason this hasn't been rolled into master? It did indeed fix the issue for me.

**Comment by lukasbestle** [comment]
The Kirby CLI is going to be phased out with Kirby 3, so we are no longer actively developing it. Sorry about that.

**Comment by peschee** [comment]
Ok, thanks for letting us know. I guess the best way to users who want this fixes is to manually apply the fix proposed by @mightymango
