### ISSUE TITLE
Warning: ZipArchive::extractTo(): Not a directory

### ISSUE THREAD

**Issue by calebgrove** [getkirby-v2/cli#39]
When attempting to install Kirby using this CLI, I get this error right after it downloads the kit:

    Warning: ZipArchive::extractTo(): Not a directory in /Users/Caleb/.composer/vendor/getkirby/cli/src/Util.php on line 21

    [RuntimeException]                       
    The source directory could not be found

    install [-k|--kit [KIT]] [--dev] [--] [<path>]

**Comment by CalebGrove** [comment]
I'm also getting this error when trying to update a plugin.

**Comment by rasteiner** [comment]
this probably is fixed by PR #47, would you try?

**Comment by calebgrove** [comment]
Well, I would, but the CLI is now working without error for me. If the issues shows up again I will give it a shot.

**Comment by rasteiner** [comment]
do you happen to have a `tmp` folder in your `/tmp` folder? Like `/tmp/tmp`... Just out of curiosity :3

**Comment by calebgrove** [comment]
No, I don't have `tmp` inside of `/tmp`

**Comment by calebgrove** [comment]
Alrighty, the problem showed up again, and I can confirm that PR #47 fixes it. Thanks @rasteiner. @bastianallgeier, could we get this merged?
