### ISSUE TITLE
kirby clear:cache does nothing

### ISSUE THREAD

**Issue by lukehatfield** [getkirby-v2/cli#49]
I've installed the Kirby CLI via Composer in my /opt/composer/vendor directory so it can be used on all websites installs on my linux server. When I type `kirby` it shows the typical response. But when I run `kirby clear:cache` it says the cache folder has been emptied, but it hasn't! 

Does this have to do with relative paths, and the cli install being installed far away from the web files?

**Comment by lukehatfield** [comment]
update: here's the output when I run `kirby clear:cache` on the server (and no cache files are cleared):

![screenshot_2018-06-28_10_42_21](https://user-images.githubusercontent.com/5399943/42041514-12ca4c02-7ac0-11e8-8ecb-6f7dbe1a463e.jpg)

**Comment by lumpysimon** [comment]
I'm seeing the same issue, on both my local machine (MacOS) and the live server (Ubuntu).
