### ISSUE TITLE
Feature: Add processing steps for Blueprints

### ISSUE THREAD

**Issue by thomasverleye** [getkirby-v2/cli#8]
I've seen this working great on some other CMS.

The idea is basically when you add a Blueprint in CLI you get some basic questions.
For instance:
-Blueprint can have pages? [Y/n]
-Blueprint can have files? [Y/n]

Maybe I'm overthinking this but this could save allot of time.

**Comment by bastianallgeier** [comment]
Something like this…

![blueprint](https://cloud.githubusercontent.com/assets/24532/13455608/cf9332da-e05e-11e5-85c2-03e6033c0626.gif)

:)

**Comment by thomasverleye** [comment]
That's exactly what I wanted to say! This is sooo awesome! 
If people don't want to get all these prompt messages I would suggest that they can do something like this:
`kirby make:blueprint projects --force`

**Comment by bastianallgeier** [comment]
Ohhhhh, the --force option is fantastic! I was already wasting some time on a concept for a shitty initial prompt "would you like to run the builder, blablabal" but that's definitely much better!

**Comment by JonasDoebertin** [comment]
I like the idea of a flag to prevent the "builder" from running.

However, I'd rather call it something like `--bare` instead of `--force`. I think that makes more sense, right?

**Comment by thomasverleye** [comment]
@JonasDoebertin @bastianallgeier 
`--bare` is indeed a better keyword for this
