### ISSUE TITLE
Feature: create:page

### ISSUE THREAD

**Issue by distantnative** [getkirby-v2/cli#9]
`kirby create:page $pagename $template`

Creates `content/$pagename/$template.txt`.
Also asks if it should create template file, blueprint, controller and model if they do not exist yet.

**Comment by luxlogica** [comment]
Maybe this command could have a few different syntaxes (and options), for different types of users:

### Option 1) Fully guided page creation, most helpful for newbies:

```
kirby create:page $pagename
```

This could trigger a "guided wizard", that would ask helpful questions, such as:

```
Will your page have sub-pages? (y/n)
Will your page accept files? (y/n)
Will your page be deletable? (y/n)
```

And this could include also a "field wizard", like this:

```
Enter a field type to add a field to your page (or 'none' to skip):
text
Enter a field title:
Main Heading
Is the field required? (y/n):
y
Text field 'Main Heading' added.
Enter a field type to add a field to your page (or 'none' to skip):
```

Once the user finished going through the whole wizard, it would automatically create:
* a blueprint file with the basic page and field options specified through the wizard
* a template file with the necessary php code to insert the values from the fields specified

### Option 2) Automatic creation, with no guidance:

```
kirby create:page $pagename -t $template -b $copyblueprint -c $copycontroller  -m $copymodel
kirby create:page $pagename -s
```

All flags would be *optional*, and would have full-text alternatives: ``--template`, `--bluprint`, `--controller` and `--model`. 

The `-t` flag could be used to specify a different name for the template.
The `-b` flag could be used to specify an existing blueprint file that should be copied as the blueprint for the page.
The `-c` flag could be used to specify an existing controller file to be copied and used as the controller for the page.
The `m` flag could be used to specify an existing model file to be copied and used as the controller for the page.

If the `-s` or `--silent` flag is used - and no other flags are present - a template and a blueprint will be created automatically, with the same name as the page.

This would allow for a truly flexible usage.

**Comment by lukasbestle** [comment]
Option 1 is already implemented for blueprints. :)

**Comment by texnixe** [comment]
I support option 2
